#!/bin/sh
ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
if [ -z "$ip" ] ; then
    ip=$(ifconfig en1 | grep inet | awk '$1=="inet" {print $2}')
fi
if [ -z "$ip" ] ; then
    ip=host.docker.internal
fi

xhost + $ip

docker run  -ti --rm \
       -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$ip:0 \
       -v "$(pwd)":/app \
       jomifred/jacamo-runss /app/$1
