#!/bin/sh
#ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
#if [ -z "$ip" ] ; then
#    ip=$(ifconfig en1 | grep inet | awk '$1=="inet" {print $2}')
#fi
#if [ -z "$ip" ] ; then
#    ip=host.docker.internal
#fi

xhost +

docker run  -ti --rm \
       -e DISPLAY=host.docker.internal:0 \
       -v "$(pwd)":/app \
       jomifred/jacamo:1.0 jacamo /app/$1
